### ISSUE TITLE
Entity.emit('destroyed', source) передает в source не объект Tank, а объект Projectile

### ISSUE THREAD

**Issue by sdelfi** [FrontHeads/tanchiki#40]
![image](https://user-images.githubusercontent.com/1927032/207919934-ed9d7534-5182-4dce-88fe-fbab97ff5c53.png)

![image](https://user-images.githubusercontent.com/1927032/207920673-992080ac-fb44-48ad-8dfe-6d012663a774.png)

**Comment by sdelfi** [comment]
Судя по всему - причина здесь
![image](https://user-images.githubusercontent.com/1927032/207920333-5899359b-78ea-460f-8351-b9dbbb522816.png)

**Comment by sapomaro** [comment]
Вообще, здесь бага нет. Урон получают от снарядов. У них тоже есть свойство role, которое такое же, как и у танка, их выпустившего.

**Comment by sapomaro** [comment]
Или что-то некорректно работает?

**Comment by sdelfi** [comment]
По изменениям, которые будут - все ок, закрыл
